export const FILTER_AGENDA_LOCATION = "FILTER_AGENDA_LOCATION";

export const SET_COMMAND_PRIMARY = 'SET_COMMAND_PRIMARY';
export const SET_COMMAND_SECONDARY = 'SET_COMMAND_SECONDARY';

export const SCHEDULE_SET_LOCATION = 'SCHEDULE_SET_LOCATION';
export const SCHEDULE_SET_TYPE = 'SCHEDULE_SET_TYPE';
export const SCHEDULE_SET_DATE = 'SCHEDULE_SET_DATE';
export const SCHEDULE_SET_COURSE = 'SCHEDULE_SET_COURSE';
export const REFRESH_CACHE = 'REFRESH_CACHE';

export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';

//async
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

export const AWAIT_AUTHENTICATION = 'AWAIT_AUTHENTICATION';
export const CANCEL_AWAIT_AUTHENTICATION = 'CANCEL_AWAIT_AUTHENTICATION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';

export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const START_LOAD_DASHBOARD = 'START_LOAD_DASHBOARD';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOAD_WORK_SUCCESS = 'LOAD_WORK_SUCCESS';
export const START_LOAD_WORK = 'START_LOAD_WORK';
export const SCHEDULE_REDIRECT = "SCHEDULE_REDIRECT";
export const SCHEDULE_RESET_REDIRECT = "SCHEDULE_RESET_REDIRECT";