export const LOAD_USERS = 'LOAD_USERS';
export const SET_COMMAND_PRIMARY = 'SET_COMMAND_PRIMARY';
export const SET_COMMAND_SECONDARY = 'SET_COMMAND_SECONDARY';

export const SCHEDULE_SET_LOCATION = 'SCHEDULE_SET_LOCATION';
export const SCHEDULE_SET_TYPE = 'SCHEDULE_SET_TYPE';
export const SCHEDULE_SET_DATE = 'SCHEDULE_SET_DATE';
export const SCHEDULE_SET_COURSE = 'SCHEDULE_SET_COURSE';
export const REFRESH_CACHE = 'REFRESH_CACHE';

export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';