export const LOAD_USERS = 'LOAD_USERS';
export const SET_COMMAND = 'SET_COMMAND';

export const SCHEDULE_SET_LOCATION = 'SCHEDULE_SET_LOCATION';
export const SCHEDULE_SET_TYPE = 'SCHEDULE_SET_TYPE';
export const SCHEDULE_SET_DATE = 'SCHEDULE_SET_DATE';
export const SCHEDULE_SET_COURSE = 'SCHEDULE_SET_COURSE';
